name: Keep Backend Alive

on:
  schedule:
    - cron: '*/14 * * * *'  # Runs every 14 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  ping_backend:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Backend
        env:
          BACKEND_URL: ${{ secrets.BACKEND_URL }}
        run: curl "$BACKEND_URL/health"
